# Generated by Django 4.0 on 2022-01-10 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('assurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='host',
            field=models.ForeignKey(auto_created=True,null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
    ]
